package com.eboy.po;
// Generated 2013-8-5 17:39:05 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Catagory generated by hbm2java
 */
public class Catagory  implements java.io.Serializable {


     private Integer catagoryId;
     private String catagoryName;
     private Set items = new HashSet(0);

    public Catagory() {
    }

	
    public Catagory(String catagoryName) {
        this.catagoryName = catagoryName;
    }
    public Catagory(String catagoryName, Set items) {
       this.catagoryName = catagoryName;
       this.items = items;
    }
   
    public Integer getCatagoryId() {
        return this.catagoryId;
    }
    
    public void setCatagoryId(Integer catagoryId) {
        this.catagoryId = catagoryId;
    }
    public String getCatagoryName() {
        return this.catagoryName;
    }
    
    public void setCatagoryName(String catagoryName) {
        this.catagoryName = catagoryName;
    }
    public Set getItems() {
        return this.items;
    }
    
    public void setItems(Set items) {
        this.items = items;
    }




}


