package com.eboy.po;
// Generated 2013-8-28 8:45:08 by Hibernate Tools 3.2.1.GA



/**
 * Comment generated by hbm2java
 */
public class Comment  implements java.io.Serializable {


     private Integer commentId;
     private Item item;
     private String commentUserName;
     private String commentContent;
     private double commentRate;

    public Comment() {
    }

	
    public Comment(Item item, String commentContent, double commentRate) {
        this.item = item;
        this.commentContent = commentContent;
        this.commentRate = commentRate;
    }
    public Comment(Item item, String commentUserName, String commentContent, double commentRate) {
       this.item = item;
       this.commentUserName = commentUserName;
       this.commentContent = commentContent;
       this.commentRate = commentRate;
    }
   
    public Integer getCommentId() {
        return this.commentId;
    }
    
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
    public String getCommentUserName() {
        return this.commentUserName;
    }
    
    public void setCommentUserName(String commentUserName) {
        this.commentUserName = commentUserName;
    }
    public String getCommentContent() {
        return this.commentContent;
    }
    
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent;
    }
    public double getCommentRate() {
        return this.commentRate;
    }
    
    public void setCommentRate(double commentRate) {
        this.commentRate = commentRate;
    }




}


