package com.eboy.po;
// Generated 2013-8-3 16:36:07 by Hibernate Tools 3.2.1.GA



/**
 * Gallary generated by hbm2java
 */
public class Gallary  implements java.io.Serializable {


     private Integer gallaryId;
     private Item item;
     private String gallaryUrl;

    public Gallary() {
    }

    public Gallary(Item item, String gallaryUrl) {
       this.item = item;
       this.gallaryUrl = gallaryUrl;
    }
   
    public Integer getGallaryId() {
        return this.gallaryId;
    }
    
    public void setGallaryId(Integer gallaryId) {
        this.gallaryId = gallaryId;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
    public String getGallaryUrl() {
        return this.gallaryUrl;
    }
    
    public void setGallaryUrl(String gallaryUrl) {
        this.gallaryUrl = gallaryUrl;
    }




}


