package com.eboy.po;
// Generated 2013-9-4 12:34:11 by Hibernate Tools 3.2.1.GA



/**
 * Gallery generated by hbm2java
 */
public class Gallery  implements java.io.Serializable {


     private Integer galleryId;
     private Item item;
     private String galleryUrl;

    public Gallery() {
    }

    public Gallery(Item item, String galleryUrl) {
       this.item = item;
       this.galleryUrl = galleryUrl;
    }
   
    public Integer getGalleryId() {
        return this.galleryId;
    }
    
    public void setGalleryId(Integer galleryId) {
        this.galleryId = galleryId;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
    public String getGalleryUrl() {
        return this.galleryUrl;
    }
    
    public void setGalleryUrl(String galleryUrl) {
        this.galleryUrl = galleryUrl;
    }




}


