package com.eboy.po;
// Generated 2013-8-3 16:36:07 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Item generated by hbm2java
 */
public class Item  implements java.io.Serializable {


     private Integer itemId;
     private Catagory catagory;
     private String itemEbayId;
     private String itemTitle;
     private byte[] itemDescription;
     private int itemQuantity;
     private double itemTax;
     private double itemShippingFee;
     private double itemPrice;
     private double itemSortScore;
     private double itemDiscount;
     private Set comments = new HashSet(0);
     private Set orders = new HashSet(0);
     private Set itemTags = new HashSet(0);
     private Set gallaries = new HashSet(0);

    public Item() {
    }

	
    public Item(Catagory catagory, String itemEbayId, String itemTitle, byte[] itemDescription, int itemQuantity, double itemTax, double itemShippingFee, double itemPrice, double itemSortScore, double itemDiscount) {
        this.catagory = catagory;
        this.itemEbayId = itemEbayId;
        this.itemTitle = itemTitle;
        this.itemDescription = itemDescription;
        this.itemQuantity = itemQuantity;
        this.itemTax = itemTax;
        this.itemShippingFee = itemShippingFee;
        this.itemPrice = itemPrice;
        this.itemSortScore = itemSortScore;
        this.itemDiscount = itemDiscount;
    }
    public Item(Catagory catagory, String itemEbayId, String itemTitle, byte[] itemDescription, int itemQuantity, double itemTax, double itemShippingFee, double itemPrice, double itemSortScore, double itemDiscount, Set comments, Set orders, Set itemTags, Set gallaries) {
       this.catagory = catagory;
       this.itemEbayId = itemEbayId;
       this.itemTitle = itemTitle;
       this.itemDescription = itemDescription;
       this.itemQuantity = itemQuantity;
       this.itemTax = itemTax;
       this.itemShippingFee = itemShippingFee;
       this.itemPrice = itemPrice;
       this.itemSortScore = itemSortScore;
       this.itemDiscount = itemDiscount;
       this.comments = comments;
       this.orders = orders;
       this.itemTags = itemTags;
       this.gallaries = gallaries;
    }
   
    public Integer getItemId() {
        return this.itemId;
    }
    
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }
    public Catagory getCatagory() {
        return this.catagory;
    }
    
    public void setCatagory(Catagory catagory) {
        this.catagory = catagory;
    }
    public String getItemEbayId() {
        return this.itemEbayId;
    }
    
    public void setItemEbayId(String itemEbayId) {
        this.itemEbayId = itemEbayId;
    }
    public String getItemTitle() {
        return this.itemTitle;
    }
    
    public void setItemTitle(String itemTitle) {
        this.itemTitle = itemTitle;
    }
    public byte[] getItemDescription() {
        return this.itemDescription;
    }
    
    public void setItemDescription(byte[] itemDescription) {
        this.itemDescription = itemDescription;
    }
    public int getItemQuantity() {
        return this.itemQuantity;
    }
    
    public void setItemQuantity(int itemQuantity) {
        this.itemQuantity = itemQuantity;
    }
    public double getItemTax() {
        return this.itemTax;
    }
    
    public void setItemTax(double itemTax) {
        this.itemTax = itemTax;
    }
    public double getItemShippingFee() {
        return this.itemShippingFee;
    }
    
    public void setItemShippingFee(double itemShippingFee) {
        this.itemShippingFee = itemShippingFee;
    }
    public double getItemPrice() {
        return this.itemPrice;
    }
    
    public void setItemPrice(double itemPrice) {
        this.itemPrice = itemPrice;
    }
    public double getItemSortScore() {
        return this.itemSortScore;
    }
    
    public void setItemSortScore(double itemSortScore) {
        this.itemSortScore = itemSortScore;
    }
    public double getItemDiscount() {
        return this.itemDiscount;
    }
    
    public void setItemDiscount(double itemDiscount) {
        this.itemDiscount = itemDiscount;
    }
    public Set getComments() {
        return this.comments;
    }
    
    public void setComments(Set comments) {
        this.comments = comments;
    }
    public Set getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set orders) {
        this.orders = orders;
    }
    public Set getItemTags() {
        return this.itemTags;
    }
    
    public void setItemTags(Set itemTags) {
        this.itemTags = itemTags;
    }
    public Set getGallaries() {
        return this.gallaries;
    }
    
    public void setGallaries(Set gallaries) {
        this.gallaries = gallaries;
    }




}


