package com.eboy.po;
// Generated 2013-9-11 8:02:44 by Hibernate Tools 3.2.1.GA



/**
 * Mlc generated by hbm2java
 */
public class Mlc  implements java.io.Serializable {


     private Integer mlcid;
     private Double mlc0;
     private Double mlc1;
     private Double mlc2;
     private Double mlc3;
     private Double mlc4;
     private Double mlc5;
     private Double mlc6;

    public Mlc() {
    }

    public Mlc(Double mlc0, Double mlc1, Double mlc2, Double mlc3, Double mlc4, Double mlc5, Double mlc6) {
       this.mlc0 = mlc0;
       this.mlc1 = mlc1;
       this.mlc2 = mlc2;
       this.mlc3 = mlc3;
       this.mlc4 = mlc4;
       this.mlc5 = mlc5;
       this.mlc6 = mlc6;
    }
   
    public Integer getMlcid() {
        return this.mlcid;
    }
    
    public void setMlcid(Integer mlcid) {
        this.mlcid = mlcid;
    }
    public Double getMlc0() {
        return this.mlc0;
    }
    
    public void setMlc0(Double mlc0) {
        this.mlc0 = mlc0;
    }
    public Double getMlc1() {
        return this.mlc1;
    }
    
    public void setMlc1(Double mlc1) {
        this.mlc1 = mlc1;
    }
    public Double getMlc2() {
        return this.mlc2;
    }
    
    public void setMlc2(Double mlc2) {
        this.mlc2 = mlc2;
    }
    public Double getMlc3() {
        return this.mlc3;
    }
    
    public void setMlc3(Double mlc3) {
        this.mlc3 = mlc3;
    }
    public Double getMlc4() {
        return this.mlc4;
    }
    
    public void setMlc4(Double mlc4) {
        this.mlc4 = mlc4;
    }
    public Double getMlc5() {
        return this.mlc5;
    }
    
    public void setMlc5(Double mlc5) {
        this.mlc5 = mlc5;
    }
    public Double getMlc6() {
        return this.mlc6;
    }
    
    public void setMlc6(Double mlc6) {
        this.mlc6 = mlc6;
    }




}


