package com.eboy.po;
// Generated 2013-8-12 15:15:00 by Hibernate Tools 3.2.1.GA



/**
 * Statistics generated by hbm2java
 */
public class Statistics  implements java.io.Serializable {


     private Integer statisticsId;
     private double statisticsIncome;
     private double statisticsOutpay;

    public Statistics() {
    }

    public Statistics(double statisticsIncome, double statisticsOutpay) {
       this.statisticsIncome = statisticsIncome;
       this.statisticsOutpay = statisticsOutpay;
    }
   
    public Integer getStatisticsId() {
        return this.statisticsId;
    }
    
    public void setStatisticsId(Integer statisticsId) {
        this.statisticsId = statisticsId;
    }
    public double getStatisticsIncome() {
        return this.statisticsIncome;
    }
    
    public void setStatisticsIncome(double statisticsIncome) {
        this.statisticsIncome = statisticsIncome;
    }
    public double getStatisticsOutpay() {
        return this.statisticsOutpay;
    }
    
    public void setStatisticsOutpay(double statisticsOutpay) {
        this.statisticsOutpay = statisticsOutpay;
    }




}


