package com.eboy.po;
// Generated 2013-9-4 12:34:11 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tag generated by hbm2java
 */
public class Tag  implements java.io.Serializable {


     private Integer tagId;
     private String tagWord;
     private Set itemTags = new HashSet(0);

    public Tag() {
    }

	
    public Tag(String tagWord) {
        this.tagWord = tagWord;
    }
    public Tag(String tagWord, Set itemTags) {
       this.tagWord = tagWord;
       this.itemTags = itemTags;
    }
   
    public Integer getTagId() {
        return this.tagId;
    }
    
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }
    public String getTagWord() {
        return this.tagWord;
    }
    
    public void setTagWord(String tagWord) {
        this.tagWord = tagWord;
    }
    public Set getItemTags() {
        return this.itemTags;
    }
    
    public void setItemTags(Set itemTags) {
        this.itemTags = itemTags;
    }




}


